Create database AssigmentJAVA3
go
use AssigmentJAVA3
go

CREATE TABLE ACCOUNT(
USERNAME   NVARCHAR(100) PRIMARY KEY,
PASSWORD   NVARCHAR(100),
ROLE       NVARCHAR(10),
)
go
INSERT ACCOUNT VALUES ('ThuKho','202cb962ac59 75b964b 7152d234b70',N'Thủ Kho')
INSERT ACCOUNT VALUES ('QuanLy','202cb962ac59 75b964b 7152d234b70',N'Quản lý')
go
SELECT*FROM ACCOUNT
------------------------------------------------------------------------//
-----------------------------------------------------------------------//
DROP TABLE CATEGORY
CREATE TABLE CATEGORY(
CATEGORYID   INT PRIMARY KEY IDENTITY(1,1),
CATEGORYNAME NVARCHAR(50)
)
INSERT  CATEGORY VALUES (N'CHIẾU RẠP')
INSERT CATEGORY VALUES (N'TRUYỀN HÌNH')
GO
select*from CATEGORY
-----------------------------------------------------------------------//
-----------------------------------------------------------------------//
select*from MOVIE cl join category cg on
cl.CATEGORYID=cg.CATEGORYID where cg.CATEGORYID
in (Select CATEGORYID from CATEGORY where CATEGORYNAME=N'CHIẾU RẠP')

CREATE TABLE MOVIE(
ID             INT PRIMARY KEY IDENTITY(1,1),
CATEGORYID     INT,
PRODUCTNAME    NCHAR(20),
CURRENTPRICE   Float,
QUANTITY       INT,
THEME		   NVARCHAR(30),
SIZE		   int,
IDLIST         BIT,
 FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(CATEGORYID)
)

INSERT MOVIE VALUES (1,N'TÂY DU KÍ','200000','87',N'VÕ THUẬT',5,1)
INSERT MOVIE VALUES (1,N'DOREEMON','100000','90',N'HOẠT HÌNH',2,1)
INSERT MOVIE VALUES (1,N'CONAN','200000','200',N'HOẠT HÌNH',4,1)
INSERT MOVIE VALUES (1,N'ĐẢO ĐẦU LÂU','800000','3',N'HÀNH ĐỘNG',6,1)
INSERT MOVIE VALUES (2,N'7 VIÊN NGỌC RỒNG','63000','155',N'HOẠT HÌNH',4,1)
INSERT MOVIE VALUES (2,N'SIM','63000','155',N'HOẠT HÌNH',6,1)

select*From MOVIE
select id From MOVIE where PRODUCTNAME =N'TÂY DU KÍ'
DELETE FROM MOVIE
DROP TABLE MOVIE
Select *from MOVIE where PRODUCTNAME like N'%DU%'
Select *from MOVIE where PRODUCTNAME like N'%v%'

-----------------------------------------------------------------------//
-----------------------------------------------------------------------//

CREATE TABLE INVENTORYLOG(
PRODUCTID  INT,
IEDATE     DATETIME,
IOE        BIT,
QUANTITY   INT,
PRICE      Float,
PRIMARY KEY(PRODUCTID,IEDATE)
)
ALTER TABLE INVENTORYLOG ADD FOREIGN KEY (PRODUCTID) REFERENCES MOVIE(ID)
INSERT INVENTORYLOG VALUES (1,'8-7-2021',1,34,500000)
INSERT INVENTORYLOG VALUES (2,'8-6-2021',1,4,50000)
INSERT INVENTORYLOG VALUES (3,'8-8-2021',1,24,40000)
INSERT INVENTORYLOG VALUES (4,'8-9-2021',1,50,505000)
INSERT INVENTORYLOG VALUES (5,'8-17-2021',1,34,500000)
INSERT INVENTORYLOG VALUES (6,'8-18-2021',1,76,440000)

INSERT INVENTORYLOG VALUES (1,'8-3-2021',0,4,50000)
INSERT INVENTORYLOG VALUES (2,'8-25-2021',0,300,40000)
INSERT INVENTORYLOG VALUES (3,'8-19-2021',0,80,57000)
INSERT INVENTORYLOG VALUES (4,'8-22-2021',0,88,345000)
INSERT INVENTORYLOG VALUES (5,'8-29-2021',0,80,57000)
INSERT INVENTORYLOG VALUES (6,'8-4-2021',0,98,98000)


Drop table INVENTORYLOG

DELETE FROM INVENTORYLOG
--------------------------------
SELECT*FROM INVENTORYLOG 
SELECT*FROM MOVIE
--3 sản phẩm nhập ít nhất tháng




select top 3 PRODUCTNAME,IOE,SUM(i.QUANTITY) as 'Tổng Sl',sum(PRICE) as 'Tổng Price'
from INVENTORYLOG i join MOVIE m on i.PRODUCTID = m.ID 
where IOE = 1
group by PRODUCTNAME,IOE
order by SUM(i.QUANTITY)
