declare @bang table(  PRODUCTID INT,  PRICE     FLOAT,   QUANTITY  INT)
INSERT @BANG select TOP 3 PRODUCTID,sum(price),sum(quantity) fromINVENTORYLOG where ioe=0 
group by PRODUCTID,ABS( MONTH(GETDATE())-MONTH(IEDATE))
ORDER BY ABS( MONTH(GETDATE())-MONTH(IEDATE)) ASC
declare @bang2  table  PRODUCTID INT, PRICE FLOAT, QUANTITY1  INT,  CATEGORYNAME nchar(10),  PRODUCTNAME nchar(30), CURRENTPRICE Float,
  QUANTITY  INT,  COLOR NCHAR(20), SIZE NCHAR(10), IOE BIT)
INSERT  @bang2 SELECT B.PRODUCTID,B.PRICE,B.QUANTITY,CG.CATEGORYNAME,CL.PRODUCTNAME,
CL.CURRENTPRICE,CL.QUANTITY, CL.COLOR,CL.SIZE, IG.IOE FROM CLOTHES CL JOIN @BANG B ON B.PRODUCTID = CL.ID
 join INVENTORYLOG IG ON B.PRODUCTID =IG.PRODUCTID
join CATEGORY CG  ON CG.CATEGORYID=CL.CATEGORYID
where cl.IDLIST=1 and ioe =0
SELECT PRODUCTID, SUM(PRICE),SUM(QUANTITY1),CATEGORYNAME,PRODUCTNAME,
CURRENTPRICE,QUANTITY,COLOR,SIZE,IOE FROM @bang2
GROUP BY  PRODUCTID, PRICE,QUANTITY1,CATEGORYNAME,PRODUCTNAME,CURRENTPRICE,QUANTITY,COLOR,SIZE,IOE 
ORDER BY SUM(PRICE) DESC";