create database PHIM
USE phim
GO
IF OBJECT_ID('PHIM') IS NOT NULL
DROP TABLE PHIM
GO
CREATE TABLE PHIM
(
MAPHIM NVARCHAR(10)NOT NULL,
TENPHIM NVARCHAR(50) NULL,
NAMSX INT NULL,
THELOAI NVARCHAR(50)NULL,
HINHTHUC NVARCHAR(50)NULL,
PHIMKINHDIEN NVARCHAR(50) NULL,
CONSTRAINT PK_PHIM PRIMARY KEY(MAPHIM)
)
update
select *from phim
INSERT INTO PHIM VALUES('PHIM01',N'HELLO CÔ BA',1961,N'HÀI',N'RẠP',N'TITANIC')